backend/config/urls.py
import oauth2_provider.urls
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path, re_path
from django.utils.translation import gettext_lazy as _
from django.views.generic.base import RedirectView
from rest_framework.authtoken import views

from core import sitemaps
from core.views import privacy, service_status, settings, terms
from pokemongo.views import edit_profile

app_name = "trainerdex"
urlpatterns = [
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("img/favicon.ico"))),
    path(
        "sitemap.xml",
        sitemap,
        {
            "sitemaps": {
                "base": sitemaps.BaseSitemap,
                "trainers": sitemaps.TrainerSitemap,
                "communities": sitemaps.LeaderboardCommunitySitemap,
            }
        },
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("api/admin/doc/", include("django.contrib.admindocs.urls")),
    path("api/admin/", admin.site.urls),
    path("api/", include("core.api.urls")),
    path("api/v1/", include("pokemongo.api.v1.urls")),
    path("api/v2/", include("pokemongo.api.v2.urls")),
    path("api/token-auth/", views.obtain_auth_token),
    path(
        "api/oauth/",
        include(
            (oauth2_provider.urls.base_urlpatterns, oauth2_provider.urls.app_name),
            namespace=oauth2_provider.urls.app_name,
        ),
    ),
    path("legal/privacy/", privacy, name="privacy"),
    path("legal/terms/", terms, name="terms"),
    path("status/", service_status, name="service_status"),
    path("settings/", settings, name="account_settings"),
    path("settings/profile/", edit_profile, name="profile_edit"),
    path("accounts/", include("allauth.urls")),
    path("", include("pokemongo.urls")),
    path("silk/", include("silk.urls", namespace="silk")),
    re_path(r"^robots\.txt", include("robots.urls")),
]

admin.site.site_title = "TrainerDex"
admin.site.site_header = _("{site_name} Admin").format(site_name=admin.site.site_title)

backend/core/api/urls.py
from django.urls import path

from core.api.views import (
    ServiceDetailView,
    ServiceListView,
    TestOAuthView,
    health_check,
)

app_name = "core.api"

urlpatterns = [
    path("services/", ServiceListView.as_view(), name="service_list"),
    path("services/<int:pk>/", ServiceDetailView.as_view(), name="service_detail"),
    path("health/", health_check),
    path("oauth/test/", TestOAuthView.as_view()),
]

backend/pokemongo/urls.py
from django.urls import path

from pokemongo.views import home, leaderboard, new_update, profile_redirector

app_name = "trainerdex"

urlpatterns = [
    path("leaderboard", leaderboard, name="leaderboard"),
    path("profile/", profile_redirector, name="profile"),
    path("profile/id/<int:id>/", profile_redirector, name="profile"),
    path("new/", new_update, name="update_stats"),
    path("u/<str:nickname>/", profile_redirector, name="profile"),
    path("", home, name="home"),
]

backend/core/models.py
# import datetime
import logging

# import requests
import django.contrib.postgres.fields
# from allauth.socialaccount.models import SocialAccount
from django.conf import settings
from django.contrib.auth.models import AbstractUser
# from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _, ngettext, npgettext_lazy
# from django.utils import timezone
from exclusivebooleanfield.fields import ExclusiveBooleanField
# from pytz import common_timezones

from trainerdex.validators import PokemonGoUsernameValidator

log = logging.getLogger('django.trainerdex')


class User(AbstractUser):
    """The model used to represent a user in the database"""
    
    username = django.contrib.postgres.fields.CICharField(
        max_length=15,
        unique=True,
        validators=[PokemonGoUsernameValidator],
        error_messages={'unique': _("A user with that username already exists.")},
    )
    gdpr = models.BooleanField(default=True)


class Nickname(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name=User._meta.verbose_name,
    )
    nickname = django.contrib.postgres.fields.CICharField(
        max_length=15,
        unique=True,
        validators=[PokemonGoUsernameValidator],
        db_index=True,
        verbose_name=npgettext_lazy("nickname__title", "nickname", "nicknames", 1),
    )
    active = ExclusiveBooleanField(
        on='user',
    )
    
    def __str__(self):
        return self.nickname
        
    class Meta:
        ordering = ['nickname']
        verbose_name = npgettext_lazy("nickname__title", "nickname", "nicknames", 1)
        verbose_name_plural = npgettext_lazy("nickname__title", "nickname", "nicknames", 2)

@receiver(post_save, sender=User)
def create_nickname(sender, instance, created, **kwargs) -> Nickname:
    if kwargs.get('raw'):
        return None
    
    if created:
        return Nickname.objects.create(user=instance, nickname=instance.username, active=True)

@receiver(post_save, sender=Nickname)
def update_username(sender, instance, created, **kwargs):
    if kwargs.get('raw'):
        return None
    
    if instance.active and instance.user.username != instance.nickname:
        instance.user.username = instance.nickname
        instance.user.save(update_fields=['username'])
        # TODO: Generate an email or notice for the user alerting them of this change.


# def get_guild_info(guild_id: int):
#     base_url = 'https://discordapp.com/api/v{version_number}'.format(version_number=6)
#     r = requests.get(f"{base_url}/guilds/{guild_id}", headers={'Authorization': f"Bot {settings.DISCORD_TOKEN}"})
#     try:
#         r.raise_for_status()
#     except requests.exceptions.HTTPError:
#         return r.status_code
#     return r.json()
#
# def get_guild_members(guild_id: int, limit=1000):
#     base_url = 'https://discordapp.com/api/v{version_number}'.format(version_number=6)
#     previous = None
#     more = True
#     result = []
#     while more:
#         r = requests.get(f"{base_url}/guilds/{guild_id}/members", headers={'Authorization': f"Bot {settings.DISCORD_TOKEN}"}, params={'limit': limit, 'after': previous})
#         r.raise_for_status()
#         more = bool(r.json())
#         if more:
#             result += r.json()
#             previous = result[-1]['user']['id']
#     return result
#
# def get_guild_member(guild_id: int, user_id: int):
#     base_url = 'https://discordapp.com/api/v{version_number}'.format(version_number=6)
#     r = requests.get(f"{base_url}/guilds/{guild_id}/members/{user_id}", headers={'Authorization': f"Bot {settings.DISCORD_TOKEN}"})
#     r.raise_for_status()
#     return r.json()
#
# def get_guild_channels(guild_id: int):
#     base_url = 'https://discordapp.com/api/v{version_number}'.format(version_number=6)
#     r = requests.get(f"{base_url}/guilds/{guild_id}/channels", headers={'Authorization': f"Bot {settings.DISCORD_TOKEN}"})
#     r.raise_for_status()
#     return r.json()
#
# def get_channel(channel_id: int):
#     base_url = 'https://discordapp.com/api/v{version_number}'.format(version_number=6)
#     r = requests.get(f"{base_url}/channels/{channel_id}", headers={'Authorization': f"Bot {settings.DISCORD_TOKEN}"})
#     r.raise_for_status()
#     return r.json()
#
#
# class DiscordGuild(models.Model):
#     id = models.BigIntegerField(
#         primary_key=True,
#         verbose_name="ID",
#     )
#     data = django.contrib.postgres.fields.JSONField(
#         null=True,
#         blank=True,
#     )
#     cached_date = models.DateTimeField(auto_now_add=True)
#     has_access = models.BooleanField(default=False)
#     members = models.ManyToManyField(
#         'DiscordUser',
#         through='DiscordGuildMembership',
#         through_fields=('guild', 'user'),
#     )
#
#     def _outdated(self):
#         return (timezone.now()-self.cached_date) > datetime.timedelta(hours=1)
#     _outdated.boolean = True
#     outdated = property(_outdated)
#
#     def has_data(self):
#         return bool(self.data)
#     has_data.boolean = True
#     has_data.short_description = _('got data')
#
#     @property
#     def name(self):
#         return self.data.get('name')
#
#     @property
#     def owner(self):
#         if self.data:
#             if 'owner_id' in self.data:
#                 try:
#                     return DiscordUser.objects.get(uid=self.data['owner_id'])
#                 except SocialAccount.DoesNotExist:
#                     pass
#             return self.data['owner_id']
#
#     def __str__(self):
#         try:
#             return str(self.name)
#         except requests.exceptions.HTTPError:
#             return f"Discord Guild with ID {self.id}"
#
#     def refresh_from_api(self):
#         logging.info(f"Updating {self}")
#         try:
#             data_or_code = get_guild_info(self.id)
#         except requests.exceptions.HTTPError:
#             log.exception("Failed to get server information from Discord")
#         else:
#             if type(data_or_code) == int:
#                 self.has_access = False
#             else:
#                 self.data = data_or_code
#                 self.has_access = True
#                 self.cached_date = timezone.now()
#                 self.sync_roles()
#             self.save()
#
#     def sync_members(self):
#         try:
#             guild_api_members = get_guild_members(self.id)
#         except requests.exceptions.HTTPError:
#             log.exception("Failed to get server information from Discord")
#             return {'warning': ["Failed to get server information from Discord"]}
#
#         # Replace with a update_or_create() loop
#
#         new_members = [DiscordGuildMembership(
#                 guild=self,
#                 user=SocialAccount.objects.get(provider='discord', uid=x["user"]["id"]),
#                 active=True,
#                 data=x,
#                 cached_date=timezone.now(),
#                 ) for x in guild_api_members if SocialAccount.objects.filter(provider='discord', uid=x["user"]["id"]).exists() and not DiscordGuildMembership.objects.filter(
#                     guild=self,
#                     user=SocialAccount.objects.get(provider='discord', uid=x["user"]["id"]),
#                 ).exists()]
#
#
#         bulk = DiscordGuildMembership.objects.bulk_create(new_members)
#
#         reactivate_members = DiscordGuildMembership.objects.filter(guild=self, active=False, user__uid__in=[x["user"]["id"] for x in guild_api_members])
#         reactivate_members.update(active=True)
#
#         inactive_members = DiscordGuildMembership.objects.filter(guild=self, active=True).exclude(user__uid__in=[x["user"]["id"] for x in guild_api_members])
#         inactive_members.update(active=False)
#
#         return {'success': [
#                     ngettext(
#                         "Succesfully imported {success} of {total} ({real_total}) new member to {guild}",
#                         "Succesfully imported {success} of {total} ({real_total}) new members to {guild}", len(new_members)
#                         ).format(success=len(bulk), total=len(new_members), real_total=len(guild_api_members), guild=self),
#                     ngettext(
#                         "Succesfully added {count} member back into {guild}",
#                         "Succesfully added {count} members back into {guild}", len(guild_api_members)
#                         ).format(count=reactivate_members.count(), guild=self)
#                 ],
#                 'warning': [
#                     ngettext(
#                         "{count} member left {guild}",
#                         "{count} members left {guild}", inactive_members.count()
#                         ).format(count=inactive_members.count(), guild=self)
#                 ]}
#
#     def clean(self):
#         self.refresh_from_api()
#
#     class Meta:
#         verbose_name = _("Discord Guild")
#         verbose_name_plural = _("Discord Guilds")
#
# class DiscordGuildSettings(DiscordGuild):
#     # Localization settings
#     language = models.CharField(default=settings.LANGUAGE_CODE, choices=settings.LANGUAGES, max_length=len(max(settings.LANGUAGES, key=lambda x: len(x[0]))[0]))
#     timezone = models.CharField(default=settings.TIME_ZONE, choices=((x, x) for x in common_timezones), max_length=len(max(common_timezones, key=len)))
#
#     # Needed for automatic renaming features
#     rename_users_on_join = models.BooleanField(
#         default=True,
#         verbose_name=_('Rename users when they join.'),
#         help_text=_("This setting will rename a user to their Pokémon Go username whenever they join your server and when their name changes on here."),
#     )
#     rename_users_on_update = models.BooleanField(

backend/core/api/views.py
from __future__ import annotations

from uuid import UUID

from django.db.models import Prefetch, QuerySet
from django.shortcuts import get_object_or_404
from oauth2_provider.contrib.rest_framework import OAuth2Authentication, TokenHasScope
from rest_framework.decorators import (
    api_view,
    authentication_classes,
    permission_classes,
)
from rest_framework.permissions import AllowAny
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.status import HTTP_204_NO_CONTENT
from rest_framework.views import APIView

from core.api.serializers import ListServiceSerializer
from core.models.main import Service, ServiceStatus


class ServiceListView(APIView):
    permission_classes = [AllowAny]

    def get(self, request: Request) -> Response:
        queryset: QuerySet[Service] = Service.objects.prefetch_related(
            Prefetch(
                "statuses",
                ServiceStatus.objects.order_by("-created_at"),
                to_attr="statuses_ordered",
            )
        )
        serializer = ListServiceSerializer(queryset, many=True)
        return Response(serializer.data)


class ServiceDetailView(APIView):
    permission_classes = [AllowAny]

    def get(self, request: Request, uuid: UUID) -> Response:
        queryset: QuerySet[Service] = Service.objects.prefetch_related(
            Prefetch(
                "statuses",
                ServiceStatus.objects.order_by("-created_at"),
                to_attr="statuses_ordered",
            )
        )
        service: Service = get_object_or_404(queryset, uuid=uuid)
        serializer = ListServiceSerializer(service)
        return Response(serializer.data)


@api_view(["GET"])
@authentication_classes([])
@permission_classes([AllowAny])
def health_check(request: Request) -> Response:
    return Response(status=HTTP_204_NO_CONTENT)


class TestOAuthView(APIView):
    """An API which does nothing but check if the OAuth2 token is authenticated and has the read scope."""

    authentication_classes = [OAuth2Authentication]
    permission_classes = [TokenHasScope]
    required_scopes = ["read"]

    def get(self, request: Request) -> Response:
        return Response(status=HTTP_204_NO_CONTENT)

backend/core/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


def settings(request: HttpRequest) -> HttpResponse:
    return render(request, "account/account_settings.html")


def privacy(request: HttpRequest) -> HttpResponse:
    return render(request, "privacy.html")


def terms(request: HttpRequest) -> HttpResponse:
    return render(request, "terms.html")


def service_status(request: HttpRequest) -> HttpResponse:
    return render(request, "status.html")

backend/core/templates/base.html
<!DOCTYPE html>
<html lang="en" prefix="og: http://ogp.me/ns#" charset="utf-8">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">

    {% load static %}
    {% load i18n %}
    {% load account %}

    <title>{% block head_title %}{% endblock %} | TrainerDex</title>
    <meta name="description" content="{% trans 'TrainerDex provides leaderboards and stats related to Pokemon Go. Join now!' context 'meta tag in head' %}">
    <meta name="mobile-web-app-capable" content="yes">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/site.webmanifest' %}">

    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />
    <meta property="og:site_name" content="TrainerDex" />
    <meta name="fb:page_id" content="1683676791663912" />
    <meta name="msvalidate.01" content="E7E20ABA1E037AC0B7E0116E01E3337A" />

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,800&amp;subset=latin-ext" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.red-pink.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/mdl-ext@0.17.1/lib/mdl-ext.min.css">
    <link rel="stylesheet" href="{% static 'css/mdl.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.wpcc.io/lib/1.0.2/cookieconsent.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.3/moment-with-locales.min.js" integrity="sha512-vFABRuf5oGUaztndx4KoAEUVQnOvAIFs59y4tO0DILGWhQiFnFHiR+ZJfxLDyJlXgeut9Z07Svuvm+1Jv89w5g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script defer src="https://cdn.wpcc.io/lib/1.0.2/cookieconsent.min.js"></script>
    <script>
      window.addEventListener(
        "load",
        function(){
          window.wpcc.init(
            {
              "corners":"small",
              "colors":{
                "popup":{
                  "background":"#f2f2f2",
                  "text":"#332e20",
                  "border":"#ca3755"
                },
                "button":{
                  "background":
                  "#ca3755",
                  "text":"#f2f2f2"
                }
              },
              "border":"normal",
              "transparency":"5",
              "content":{
                "href":"{% url 'privacy' %}",
                "button":"{% trans "OK" context "general_ok" %}",
                "link":"{% trans "Learn more" %}",
                "message":"{% trans "This website uses cookies to ensure you get the best experience on our website." %}"
              }
            }
          )
        }
      );
    </script>



    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-5522637786617178",
        enable_page_level_ads: true
      });
    </script>

    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="trainerdex-header mdl-layout__header is-casting-shadow">
        <div class="mdl-layout__header-row">
          <span class="trainerdex-logo mdl-layout__title">
            <img src="{% static 'svg/logo-text.svg' %}">
          </span>
          <div class="mdl-layout-spacer"></div>
          {# Navigation #}
          <div class="trainerdex-header-navigation-container">
            <nav class="trainerdex-header-navigation mdl-navigation">
              <a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'trainerdex:leaderboard' %}">{% trans "Leaderboard" %}</a>
              {% comment %} {% if user.trainer.country_iso %}<a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'trainerdex:leaderboard' country=user.trainer.country_iso %}">{{user.trainer.country_iso}} {% trans "Leaderboard" %}</a>{% endif %} {% endcomment %}
              {% if user.is_authenticated %}
              <a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'trainerdex:profile' %}">{% user_display user %}</a>
              <a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'account_logout' %}">{% trans "Sign Out" context "general_sign_out" %}</a>
              {% else %}
              <a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'account_login' %}">{% trans "Login" %}</a>
              {% endif %}
            </nav>
          </div>
        </div>
      </header>
      <div class="trainerdex-drawer mdl-layout__drawer mdl-color--primary-dark mdl-color-text--primary-contrast">
        <nav class="trainerdex-navigation mdl-navigation mdl-color--primary mdl-color-text--primary-contrast">
          {%if user.is_authenticated %}
          <a class="mdl-navigation__link mdl-menu__item--full-bleed-divider" href="{% url 'trainerdex:profile' %}"><i class="material-icons">person</i>{% user_display user %}</a>
          <a class="mdl-navigation__link" href="{% url 'account_settings' %}"><i class="material-icons" role="presentation">settings</i>{% trans "Settings" %}</a>
          <a class="mdl-navigation__link mdl-menu__item--full-bleed-divider" href="{% url 'account_logout' %}"><i class="material-icons" role="presentation">close</i>{% trans "Sign Out" context "general_sign_out" %}</a>
          {% else %}
          <a class="mdl-navigation__link" href="{% url 'account_login' %}"><i class="material-icons" role="presentation">login</i>{% trans "Login" %}</a>
          {% endif %}
          <a class="mdl-navigation__link" href="{% url 'trainerdex:leaderboard' %}"><i class="material-icons" role="presentation">assessment</i>{% trans "Leaderboard" %}</a>
          {% comment %} {% if user.trainer.country_iso %}<a class="mdl-navigation__link" href="{% url 'trainerdex:leaderboard' country=user.trainer.country_iso %}"><div class="material-icons" role="presentation">{{user.trainer.flag_emoji}}</div></a>{% endif %} {% endcomment %}
          <div class="mdl-menu__item--full-bleed-divider"></div>
          <div class="mdl-layout-spacer"></div>
          {% if user.is_staff %}<a class="mdl-navigation__link mdl-menu__item--full-bleed-divider" href="{% url 'admin:index' %}">{% trans "Admin Panel" %}</a>{% endif %}
          <a class="mdl-navigation__link" href="{% url 'privacy' %}">{% trans "Privacy Policy" %}</a>
          <a class="mdl-navigation__link mdl-menu__item--full-bleed-divider" href="{% url 'terms' %}">{% trans 'Terms of Service' %}</a>
          <a class="mdl-navigation__link mdl-menu__item--full-bleed-divider" href="https://discord.gg/pFhMS3s">{% trans "Join our Discord server!" %}</a>
          <a class="mdl-navigation__link" href="https://github.com/TurnrDev">{% trans 'Author' %}: TurnrDev</a>
          <a class="mdl-navigation__link">{% trans 'Version' %}: {{tdx_version}}</a>
        </nav>
      </div>

      {% if messages %}{% for message in messages %}
      <div id="trainerdex-toast-message" class="mdl-js-snackbar mdl-snackbar">
        <div class="mdl-snackbar__text"></div>
        <button class="mdl-snackbar__action" type="button"></button>
      </div>
      <script>
      r(function(){
          var snackbarContainer = document.querySelector('#trainerdex-toast-message');
          var data = { message: '{{message}}'};
          snackbarContainer.MaterialSnackbar.showSnackbar(data);
      });
      function r(f){ /in/.test(document.readyState)?setTimeout('r('+f+')',9):f()}
      </script>
      {% endfor %}{% endif %}

      {% block page %}
      <main class="mdl-layout__content mdl-color--grey-100" style="flex: 1 0 auto;">
        {% block content %}
        {% endblock %}
      </main>
      {% endblock %}

      {% endblock %}
      {% block extra_body %}
      {% endblock %}
    </div>

    {% block fab %}
    {% if user.is_authenticated %}
    <a id="trainerdex__fab" class="mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-button--raised mdl-js-ripple-effect mdl-button--colored" href="{% url 'trainerdex:update_stats' %}"><i class="material-icons">add</i></a>
    {% endif %}
    {% endblock %}

    {% if GOOGLE_ANALYTICS_MEASUREMENT_ID %}
      {% include "ga.html" %}
    {% endif %}
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/mdl-ext@0.17.1/lib/mdl-ext.min.js"></script>
  </body>
</html>

backend/core/templates/ga.html
{% load account %}

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{GOOGLE_ANALYTICS_MEASUREMENT_ID}}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  {% if user.is_authenticated %}
  gtag('config', '{{GOOGLE_ANALYTICS_MEASUREMENT_ID}}', {'user_id': '{{user.id}}'});
  {% else %}
  gtag('config', '{{GOOGLE_ANALYTICS_MEASUREMENT_ID}}');
  {% endif %}
</script>

backend/core/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" charset="utf-8">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>TrainerDex</title>
        <base href="/">
        <meta name="description" content="Join TrainerDex">
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="apple-touch-icon" sizes="180x180" href="/img/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/img/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/img/favicon-16x16.png">
        <link rel="icon" href="/favicon.ico">
        <meta property="og:site_name" content="TrainerDex" />
        <meta name="fb:page_id" content="1683676791663912" />
        <meta name="msvalidate.01" content="E7E20ABA1E037AC0B7E0116E01E3337A" />
        
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic|Material+Icons">
    </head>
    <body>
        <noscript>
            <strong>We're sorry but TrainerDex doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
        </noscript>
        
    </body>
</html>